configure
git-svn-id: svn://svn.r-forge.r-project.org/svnroot/rgdal@58 edb9625f-4e0d-4859-8d74-9fd3b1da38cb

diff --git a/trunk/configure b/trunk/configure
--- a/trunk/configure
+++ b/trunk/configure
@@ -1338,6 +1338,14 @@ if test "$VER12" != "$REQ_GDAL" ; then
     exit 1
 fi
 
+: ${R_HOME=`R RHOME`}
+          if test -z "${R_HOME}"; then
+            echo "could not determine R_HOME"
+            exit 1
+fi
+CC=`"${R_HOME}/bin/R" CMD config CC`
+CFLAGS=`"${R_HOME}/bin/R" CMD config CFLAGS`
+
 
 # Check whether --with-proj-include or --without-proj-include was given.
 if test "${with_proj_include+set}" = set; then
diff --git a/trunk/configure.in b/trunk/configure.in
--- a/trunk/configure.in
+++ b/trunk/configure.in
@@ -41,6 +41,14 @@ if test "$VER12" != "$REQ_GDAL" ; then
     exit 1
 fi
 
+: ${R_HOME=`R RHOME`}
+          if test -z "${R_HOME}"; then
+            echo "could not determine R_HOME"
+            exit 1
+fi
+CC=`"${R_HOME}/bin/R" CMD config CC`
+CFLAGS=`"${R_HOME}/bin/R" CMD config CFLAGS`
+
 AC_ARG_WITH([proj-include],
     AC_HELP_STRING([--with-proj-include=INCLUDE_PATH],
            [the location of proj header files]),
