run silent on OSX/static against GDAL3.0.0, PROJ6.1.0
git-svn-id: svn://svn.r-forge.r-project.org/svnroot/rgdal@834 edb9625f-4e0d-4859-8d74-9fd3b1da38cb

diff --git a/pkg/configure b/pkg/configure
--- a/pkg/configure
+++ b/pkg/configure
@@ -2336,8 +2336,12 @@ $as_echo "$as_me: PROJ_LIB: ${proj_share_path}" >&6;}
 fi
 
 
-
 if test ${PROJ6} = "no"; then
+
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking PROJ.6: " >&5
+$as_echo_n "checking PROJ.6: ... " >&6; }
+{ $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
 
 cat > proj_conf_test2.c <<_EOCONF
 #include <stdio.h>
@@ -2399,7 +2403,7 @@ fi
 
 else # test for new files if PROJ6
 
-cat > proj_conf_test2.c <<_EOCONF
+cat > proj_conf_test2.cpp <<_EOCONF
 #include <stdio.h>
 #include <proj_api.h>
 
@@ -2414,7 +2418,7 @@ int main() {
 }
 _EOCONF
 
-${CC} ${CFLAGS} ${PKG_CPPFLAGS} -o proj_conf_test2 proj_conf_test2.c ${PKG_LIBS}
+${CXX} ${CPPFLAGS} ${PKG_CPPFLAGS} -o proj_conf_test2 proj_conf_test2.cpp ${PKG_LIBS} -lproj -lsqlite3
 if test  -n "$proj_share_path"  ; then
   PROJ_LIB="${proj_share_path}" ./proj_conf_test2
   proj_share=`echo $?`
@@ -2423,8 +2427,8 @@ else
   proj_share=`echo $?`
 fi
 
-{ $as_echo "$as_me:${as_lineno-$LINENO}: checking PROJ.4: proj.db found and readable" >&5
-$as_echo_n "checking PROJ.4: proj.db found and readable... " >&6; }
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking PROJ: proj.db found and readable" >&5
+$as_echo_n "checking PROJ: proj.db found and readable... " >&6; }
 if test ${proj_share} -eq 1 ; then
     { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
 $as_echo "no" >&6; }
@@ -2434,7 +2438,7 @@ else
 $as_echo "yes" >&6; }
 fi
 
-rm -f proj_conf_test2.c proj_conf_test2
+rm -f proj_conf_test2.cpp proj_conf_test2
 
 if test "$STOP" = "stop" ; then
     echo "Error: proj/proj.db not found"
@@ -2443,7 +2447,6 @@ if test "$STOP" = "stop" ; then
     echo "configure argument."
     exit 1
 fi
-
 
 fi # don't test for old files if PROJ6
 
@@ -2474,35 +2477,36 @@ int main() {
 }
 _EOCONF
 
-${CC} ${CFLAGS} ${PKG_CPPFLAGS} -o proj_conf_test3 proj_conf_test3.c ${PKG_LIBS}
-if test  -n "$proj_share_path"  ; then
-  PROJ_LIB="${proj_share_path}" ./proj_conf_test3
-  proj_share=`echo $?`
-else
-  ./proj_conf_test3
-  proj_share=`echo $?`
-fi
+if test ${PROJ6} = "no"; then
+ ${CC} ${CFLAGS} ${PKG_CPPFLAGS} -o proj_conf_test3 proj_conf_test3.c ${PKG_LIBS}
+ if test  -n "$proj_share_path"  ; then
+   PROJ_LIB="${proj_share_path}" ./proj_conf_test3
+   proj_share=`echo $?`
+ else
+   ./proj_conf_test3
+   proj_share=`echo $?`
+ fi
 
-{ $as_echo "$as_me:${as_lineno-$LINENO}: checking PROJ.4: conus found and readable" >&5
+ { $as_echo "$as_me:${as_lineno-$LINENO}: checking PROJ.4: conus found and readable" >&5
 $as_echo_n "checking PROJ.4: conus found and readable... " >&6; }
-if test ${proj_share} -eq 1 ; then
-    WARN="warn"
-    { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+ if test ${proj_share} -eq 1 ; then
+     WARN="warn"
+     { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
 $as_echo "no" >&6; }
-else
-    { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+ else
+     { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
 $as_echo "yes" >&6; }
+ fi
+
+ if test "$WARN" = "warn" ; then
+     echo "Note: proj/conus not found"
+     echo "No support available in PROJ4 for NAD grid datum transformations"
+     echo "If required, consider re-installing from source with the contents"
+     echo "of proj-datumgrid-1.<latest>.zip from http://download.osgeo.org/proj/ in nad/."
+ fi
 fi
 
 rm -f proj_conf_test3.c proj_conf_test3
-
-if test "$WARN" = "warn" ; then
-    echo "Note: proj/conus not found"
-    echo "No support available in PROJ4 for NAD grid datum transformations"
-    echo "If required, consider re-installing from source with the contents"
-    echo "of proj-datumgrid-1.<latest>.zip from http://download.osgeo.org/proj/ in nad/."
-fi
-
 
 # Optional local copy of GDAL datadir and PROJ_LIB
 
