add data readability tests to configure.ac
git-svn-id: svn://svn.r-forge.r-project.org/svnroot/rgdal@330 edb9625f-4e0d-4859-8d74-9fd3b1da38cb

diff --git a/pkg/configure b/pkg/configure
--- a/pkg/configure
+++ b/pkg/configure
@@ -3019,6 +3019,15 @@ fi
 
 rm -f gdal_test errors.txt gdal_test.c
 
+GDAL_DATA_TEST_FILE="${GDAL_DATADIR}/epsg.wkt"
+if test -r "${GDAL_DATA_TEST_FILE}" ; then
+  echo "GDAL: ${GDAL_DATA_TEST_FILE} is readable"
+else
+  { { echo "$as_me:$LINENO: error: epsg.wkt not found in GDAL data directory." >&5
+echo "$as_me: error: epsg.wkt not found in GDAL data directory." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
 # PROJ.4
 
 
@@ -3356,6 +3365,8 @@ ${CC} ${CFLAGS} ${PKG_CPPFLAGS} -o proj_conf_test proj_conf_test.c ${PKG_LIBS} -
 proj_share=`echo $?`
 if test ${proj_share} -eq 1 ; then
     STOP="stop"
+else
+    echo "PROJ.4: epsg found and readable"
 fi
 
 rm -f proj_conf_test.c proj_conf_test
@@ -3406,6 +3417,8 @@ ${CC} ${CFLAGS} ${PKG_CPPFLAGS} -o proj_conf_test proj_conf_test.c ${PKG_LIBS} -
 proj_share=`echo $?`
 if test ${proj_share} -eq 1 ; then
     WARN="warn"
+else
+    echo "PROJ.4: conus found and readable"
 fi
 
 rm -f proj_conf_test.c proj_conf_test
