correct if nesting in configure
git-svn-id: svn://svn.r-forge.r-project.org/svnroot/rgdal@334 edb9625f-4e0d-4859-8d74-9fd3b1da38cb

diff --git a/pkg/configure b/pkg/configure
--- a/pkg/configure
+++ b/pkg/configure
@@ -3457,8 +3457,12 @@ fi;
     if test -d "${proj_lib}" ; then
       cp -r "${proj_lib}" "${R_PACKAGE_DIR}"
       echo "  PROJ.4: ${proj_lib}"
-    fi
     else
+      { { echo "$as_me:$LINENO: error: PROJ.4 data files not found; set environment variable PROJ_LIB=DIR or --with-proj-data=DIR." >&5
+echo "$as_me: error: PROJ.4 data files not found; set environment variable PROJ_LIB=DIR or --with-proj-data=DIR." >&2;}
+   { (exit 1); exit 1; }; }
+    fi
+  else
       { { echo "$as_me:$LINENO: error: PROJ.4 data files not found; set environment variable PROJ_LIB=DIR or --with-proj-data=DIR." >&5
 echo "$as_me: error: PROJ.4 data files not found; set environment variable PROJ_LIB=DIR or --with-proj-data=DIR." >&2;}
    { (exit 1); exit 1; }; }
